import fs from 'node:fs/promises'
import path from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import { describe, expect, it } from 'vitest'

describe('Detección de drift entre OpenAPI y tipos TypeScript generados', () => {
  it('los tipos TypeScript en src/esquema.ts coinciden exactamente con openapi/openapi.json', async () => {
    const rutaOpenApi = path.resolve(__dirname, '../openapi/openapi.json')
    const rutaEsquemaTs = path.resolve(__dirname, '../src/esquema.ts')

    const contenidoOpenApi = await fs.readFile(rutaOpenApi, 'utf-8')
    const jsonOpenApi = JSON.parse(contenidoOpenApi)

    const ast = await openapiTS(jsonOpenApi)
    const tsGenerado = `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n${astToString(ast)}`

    const tsActual = await fs.readFile(rutaEsquemaTs, 'utf-8')

    // Normalizamos saltos de línea para evitar discrepancias de CRLF/LF
    const normalizar = (s: string) => s.replace(/\r\n/g, '\n').trim()
    expect(normalizar(tsActual)).toBe(normalizar(tsGenerado))
  })

  it('detecta drift cuando el esquema OpenAPI contiene cambios no reflejados en TypeScript', async () => {
    const esquemaModificado = {
      openapi: '3.1.0',
      info: { title: 'Test Drift', version: '1.0.0' },
      paths: {
        '/api/v1/nuevo_endpoint_fantasma': {
          get: {
            operationId: 'endpoint_fantasma',
            responses: {
              200: {
                description: 'OK',
              },
            },
          },
        },
      },
    }

    const ast = await openapiTS(esquemaModificado)
    const tsGenerado = astToString(ast)

    const rutaEsquemaTs = path.resolve(__dirname, '../src/esquema.ts')
    const tsActual = await fs.readFile(rutaEsquemaTs, 'utf-8')

    expect(tsActual).not.toContain('/api/v1/nuevo_endpoint_fantasma')
    expect(tsGenerado).toContain('/api/v1/nuevo_endpoint_fantasma')
  })
})
