/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar Salud
         * @description Confirma disponibilidad técnica sin leer ni modificar estado operativo.
         */
        get: operations["consultar_salud_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preparacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preparar Sala
         * @description Inicia una nueva preparación de sala (CU-01).
         *
         *     Carga y congela ``config/system.toml`` y ``config/concejales.csv``, crea
         *     el conjunto de auditoría L1/L2/L3, persiste ``PREPARACION_INICIADA`` y
         *     recién entonces deja el sistema en ``PREPARANDO`` con todos los
         *     concejales ausentes. Si algún paso obligatorio falla, no se confirma
         *     éxito y el sistema permanece en ``SIN_PREPARAR``.
         */
        post: operations["preparar_sala_api_v1_preparacion_post"];
        /**
         * Cancelar Preparacion
         * @description Cancela la preparación activa (CU-02), sin recibir ni exigir motivo.
         *
         *     Persiste ``PREPARACION_CANCELADA``, cierra definitivamente los tres CSV
         *     (que se conservan en disco) y devuelve el sistema a ``SIN_PREPARAR`` con
         *     el contexto operativo completamente descartado. Si la auditoría no puede
         *     garantizar esos pasos, no se confirma la cancelación y el estado
         *     permanece en ``PREPARANDO`` en fallo cerrado.
         */
        delete: operations["cancelar_preparacion_api_v1_preparacion_delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar número y autoridades de la preparación
         * @description Aplica uno o más cambios efectivos con auditoría previa y ordenada.
         */
        patch: operations["actualizar_preparacion_api_v1_preparacion_patch"];
        trace?: never;
    };
    "/api/v1/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir la sesión preparada
         * @description Abre sin body y solo después de auditar todas sus precondiciones.
         */
        post: operations["abrir_sesion_api_v1_sesion_post"];
        /**
         * Cerrar normalmente la sesión
         * @description Cierra sin body y resuelve antes una EN_CURSO o EMPATADA pendiente.
         */
        delete: operations["cerrar_sesion_api_v1_sesion_delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar autoridades de la sesión
         * @description Cambia una o ambas autoridades; el número no integra este modelo.
         */
        patch: operations["actualizar_sesion_api_v1_sesion_patch"];
        trace?: never;
    };
    "/api/v1/votaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir una votación
         * @description Valida el body, abre bajo exclusión y devuelve la entidad normalizada.
         */
        post: operations["abrir_votacion_api_v1_votaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/votaciones/{id}/finalizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalizar manualmente una votación como inconclusa
         * @description Aplica el motivo validado sobre la votación exacta bajo exclusión.
         */
        post: operations["finalizar_votacion_api_v1_votaciones__id__finalizacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/votaciones/{id}/desempate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emitir el desempate presidencial
         * @description Desempata la votación exacta con la Presidencia vigente del backend.
         */
        post: operations["desempatar_votacion_api_v1_votaciones__id__desempate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entradas/tecla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Procesar una pulsación lógica de dispositivo
         * @description Procesa ``{dispositivo, tecla}`` y devuelve aceptación o rechazo estable.
         *
         *     FastAPI ejecuta la validación de ``SolicitudTecla`` antes de entrar aquí, de
         *     modo que un body inválido responde ``422`` sin tocar el estado ni la
         *     auditoría. Para un body válido, el servicio reutiliza el serializador único;
         *     si el writer falla, la excepción se transforma en ``503`` por el manejador
         *     compartido de auditoría.
         */
        post: operations["procesar_tecla_api_v1_entradas_tecla_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orden-del-dia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cargar y normalizar archivo de Orden del Día
         * @description Recibe un archivo CSV, lo valida atómicamente y lo instala en el contexto activo.
         */
        post: operations["cargar_orden_del_dia_api_v1_orden_del_dia_post"];
        /**
         * Descartar el Orden del Día activo
         * @description Descarta la colección activa. Si no existía colección, es un no-op exitoso.
         */
        delete: operations["descartar_orden_del_dia_api_v1_orden_del_dia_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/palabra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Otorgar palabra al primer pedido FIFO
         * @description Finaliza al orador actual y otorga el primer pedido, sin body.
         */
        post: operations["otorgar_palabra_api_v1_palabra_post"];
        /**
         * Finalizar el uso actual sin avanzar la cola
         * @description Finaliza al orador si existe y conserva toda la cola pendiente.
         */
        delete: operations["quitar_palabra_api_v1_palabra_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estado/moderacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener snapshot completo de Moderación
         * @description Responde en cualquiera de los tres estados globales sin mutar dominio.
         */
        get: operations["obtener_estado_moderacion_api_v1_estado_moderacion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estado/recinto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener snapshot público completo del Recinto
         * @description Responde el DTO restrictivo que nunca incluye votos durante EN_CURSO.
         */
        get: operations["obtener_estado_recinto_api_v1_estado_recinto_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estado/moderacion/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seguir estados completos de Moderación por SSE
         * @description Envía un primer snapshot inmediato y luego revisiones completas.
         */
        get: operations["transmitir_estado_moderacion_api_v1_estado_moderacion_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estado/recinto/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seguir estados públicos completos del Recinto por SSE
         * @description Usa exactamente el mismo constructor público restrictivo que REST.
         */
        get: operations["transmitir_estado_recinto_api_v1_estado_recinto_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remapeos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar captura física para un dispositivo lógico existente
         * @description Valida estado/padrón, genera UUID y ordena captura al bridge.
         */
        post: operations["iniciar_remapeo_api_v1_remapeos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/remapeos/{remapeo_id}/candidato": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Informar candidato físico desde el device-bridge (interno)
         * @description Congela el primer candidato sin aplicar el mapping.
         */
        post: operations["informar_candidato_api_v1_interno_remapeos__remapeo_id__candidato_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remapeos/{remapeo_id}/confirmacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autorizar y aplicar el candidato temporal o persistentemente
         * @description Persiste L3 de autorización antes de ordenar el apply físico.
         */
        post: operations["confirmar_remapeo_api_v1_remapeos__remapeo_id__confirmacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remapeos/{remapeo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancelar la captura sin modificar el mapping
         * @description Cancela idempotentemente el mismo ID en backend y bridge.
         */
        delete: operations["cancelar_remapeo_api_v1_remapeos__remapeo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccionPalabra
         * @description Acciones estables que puede producir una tecla física ``7``.
         * @enum {string}
         */
        AccionPalabra: "PEDIDO_AGREGADO" | "PEDIDO_RETIRADO" | "USO_FINALIZADO";
        /**
         * BaseMayoria
         * @description Representa el denominador conceptual de una regla de mayoría.
         *
         *     ``VOTOS_COMPUTABLES`` cuenta positivos y negativos. ``PRESENTES`` es el
         *     término institucional para quienes emitieron voto ordinario en esa
         *     votación, incluidas abstenciones. ``CUERPO`` es el total del padrón
         *     congelado. La elección se almacena al abrir y WP-011 la consume al cerrar.
         * @enum {string}
         */
        BaseMayoria: "VOTOS_COMPUTABLES" | "PRESENTES" | "CUERPO";
        /** Body_cargar_orden_del_dia_api_v1_orden_del_dia_post */
        Body_cargar_orden_del_dia_api_v1_orden_del_dia_post: {
            /**
             * Archivo
             * @description Archivo CSV canónico de seis columnas del Orden del Día.
             */
            archivo: string;
        };
        /**
         * Capacidad
         * @description Indica disponibilidad actual y códigos estables que explican el bloqueo.
         */
        Capacidad: {
            /** Habilitada */
            habilitada: boolean;
            /** Motivos */
            motivos?: string[];
        };
        /**
         * CapacidadesModeracion
         * @description Precondiciones derivables sin intentar validar bodies futuros.
         */
        CapacidadesModeracion: {
            preparar_sala: components["schemas"]["Capacidad"];
            actualizar_preparacion: components["schemas"]["Capacidad"];
            cancelar_preparacion: components["schemas"]["Capacidad"];
            abrir_sesion: components["schemas"]["Capacidad"];
            actualizar_sesion: components["schemas"]["Capacidad"];
            cerrar_sesion: components["schemas"]["Capacidad"];
            cargar_orden_del_dia: components["schemas"]["Capacidad"];
            descartar_orden_del_dia: components["schemas"]["Capacidad"];
            abrir_votacion: components["schemas"]["Capacidad"];
            finalizar_votacion: components["schemas"]["Capacidad"];
            desempatar: components["schemas"]["Capacidad"];
            otorgar_palabra: components["schemas"]["Capacidad"];
            quitar_palabra: components["schemas"]["Capacidad"];
            iniciar_remapeo: components["schemas"]["Capacidad"];
            confirmar_remapeo: components["schemas"]["Capacidad"];
            cancelar_remapeo: components["schemas"]["Capacidad"];
        };
        /**
         * CargaOrdenDelDiaRespuesta
         * @description Respuesta exitosa de carga con la lista de puntos normalizados.
         */
        CargaOrdenDelDiaRespuesta: {
            /**
             * Puntos
             * @description Colección de puntos normalizados del Orden del Día.
             */
            puntos: components["schemas"]["PuntoOrdenDelDiaRespuesta"][];
        };
        /**
         * ConcejalModeracion
         * @description Banca completa disponible para el operador institucional.
         */
        ConcejalModeracion: {
            /** Dni */
            dni: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Bloque */
            bloque: string;
            /** Banca */
            banca: number;
            /** Dispositivo Votacion */
            dispositivo_votacion: string;
            /** Ruta Imagen */
            ruta_imagen: string;
            /** Presente */
            presente: boolean;
            /** Test Activo */
            test_activo: boolean;
            /** Test Expira En */
            test_expira_en: string | null;
        };
        /**
         * ConcejalPublico
         * @description Banca pública por allowlist, sin DNI ni identificador de dispositivo.
         */
        ConcejalPublico: {
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Bloque */
            bloque: string;
            /** Banca */
            banca: number;
            /** Ruta Imagen */
            ruta_imagen: string;
            /** Presente */
            presente: boolean;
            /** Test Activo */
            test_activo: boolean;
            /** Test Expira En */
            test_expira_en: string | null;
        };
        /**
         * ConfiguracionProyectada
         * @description Configuración congelada necesaria para construir la UI de Moderación.
         */
        ConfiguracionProyectada: {
            /** Quorum */
            quorum: number;
            /** Filas Bancas */
            filas_bancas: number[];
            /** Tipos Votacion */
            tipos_votacion: string[];
            /** Duracion Test Segundos */
            duracion_test_segundos: number;
            /** Revelado Votos Moderacion Segundos */
            revelado_votos_moderacion_segundos: number;
            /** Cuenta Regresiva Recinto Segundos */
            cuenta_regresiva_recinto_segundos: number;
            /** Resultado Publico Recinto Segundos */
            resultado_publico_recinto_segundos: number;
        };
        /**
         * ConteosVotosProyectados
         * @description Conteos derivados que nunca incluyen el voto presidencial.
         */
        ConteosVotosProyectados: {
            /** Positivos */
            positivos: number;
            /** Negativos */
            negativos: number;
            /** Abstenciones */
            abstenciones: number;
            /** Total */
            total: number;
        };
        /**
         * DatosPreparacion
         * @description Identifica el contexto que todavía no es una sesión formal.
         */
        DatosPreparacion: {
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /** Numero Sesion */
            numero_sesion: number | null;
            /** Presidencia */
            presidencia: string | null;
            /** Secretaria Legislativa */
            secretaria_legislativa: string | null;
        };
        /**
         * DatosSesion
         * @description Identifica la sesión formal y sus autoridades vigentes.
         */
        DatosSesion: {
            /**
             * Fecha Hora Inicio Preparacion
             * Format: date-time
             */
            fecha_hora_inicio_preparacion: string;
            /**
             * Fecha Hora Apertura
             * Format: date-time
             */
            fecha_hora_apertura: string;
            /** Numero Sesion */
            numero_sesion: number;
            /** Presidencia */
            presidencia: string;
            /** Secretaria Legislativa */
            secretaria_legislativa: string;
        };
        /**
         * ErrorRespuesta
         * @description Cuerpo JSON estable de toda respuesta de error funcional/técnica.
         *
         *     ``codigo`` es el identificador estable legible por máquina; ``mensaje``
         *     aporta diagnóstico humano seguro (nunca trazas ni datos internos).
         */
        ErrorRespuesta: {
            /** Codigo */
            codigo: string;
            /** Mensaje */
            mensaje: string;
        };
        /**
         * EstadoAuditoriaProyectado
         * @description Condición técnica del escritor, separada del estado reglamentario.
         */
        EstadoAuditoriaProyectado: {
            /** Activa */
            activa: boolean;
            /** Disponible */
            disponible: boolean;
            /** Fallado */
            fallado: boolean;
            /** Cerrado */
            cerrado: boolean;
            /** Motivo */
            motivo: string | null;
        };
        /**
         * EstadoGlobal
         * @description Representa las únicas etapas globales permitidas por el dominio.
         *
         *     Declarar los valores en un tipo evita que servicios futuros guarden textos
         *     arbitrarios. Que los tres valores existan aquí no habilita sus transiciones:
         *     cada una es responsabilidad del Work Package que la implementa.
         * @enum {string}
         */
        EstadoGlobal: "SIN_PREPARAR" | "PREPARANDO" | "SESION_ABIERTA";
        /**
         * EstadoModeracion
         * @description Snapshot completo y reconstruible del frontend de Moderación.
         */
        EstadoModeracion: {
            /** Revision */
            revision: number;
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
            estado_global: components["schemas"]["EstadoGlobal"];
            preparacion: components["schemas"]["DatosPreparacion"] | null;
            sesion: components["schemas"]["DatosSesion"] | null;
            configuracion: components["schemas"]["ConfiguracionProyectada"] | null;
            /** Concejales */
            concejales: components["schemas"]["ConcejalModeracion"][];
            quorum: components["schemas"]["EstadoQuorum"] | null;
            votacion: components["schemas"]["VotacionModeracion"] | null;
            palabra: components["schemas"]["EstadoPalabraModeracion"] | null;
            /** Orden Del Dia */
            orden_del_dia: components["schemas"]["PuntoOrdenDelDiaProyectado"][];
            /** Eventos Recientes */
            eventos_recientes: components["schemas"]["EventoRecienteProyectado"][];
            auditoria: components["schemas"]["EstadoAuditoriaProyectado"];
            remapeo: components["schemas"]["EstadoRemapeoModeracion"] | null;
            capacidades: components["schemas"]["CapacidadesModeracion"];
        };
        /**
         * EstadoPalabraModeracion
         * @description Copia ordenada de la única cola y el único orador del dominio.
         */
        EstadoPalabraModeracion: {
            /** Cola */
            cola: components["schemas"]["PersonaPalabraModeracion"][];
            orador: components["schemas"]["PersonaPalabraModeracion"] | null;
        };
        /**
         * EstadoPalabraPublico
         * @description Versión pública del uso de palabra.
         */
        EstadoPalabraPublico: {
            /** Cola */
            cola: components["schemas"]["PersonaPalabraPublica"][];
            orador: components["schemas"]["PersonaPalabraPublica"] | null;
        };
        /**
         * EstadoQuorum
         * @description Expone los cálculos de quórum para que la UI no los reimplemente.
         */
        EstadoQuorum: {
            /** Cantidad Presentes */
            cantidad_presentes: number;
            /** Requerido */
            requerido: number;
            /** Alcanzado */
            alcanzado: boolean;
        };
        /**
         * EstadoRecinto
         * @description Snapshot público por allowlist, sin capacidades ni auditoría cruda.
         */
        EstadoRecinto: {
            /** Revision */
            revision: number;
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
            estado_global: components["schemas"]["EstadoGlobal"];
            preparacion: components["schemas"]["DatosPreparacion"] | null;
            sesion: components["schemas"]["DatosSesion"] | null;
            /** Filas Bancas */
            filas_bancas: number[] | null;
            /** Concejales */
            concejales: components["schemas"]["ConcejalPublico"][];
            quorum: components["schemas"]["EstadoQuorum"] | null;
            votacion: components["schemas"]["VotacionPublica"] | null;
            palabra: components["schemas"]["EstadoPalabraPublico"] | null;
            /** Eventos Publicos */
            eventos_publicos: components["schemas"]["EventoPublicoProyectado"][];
        };
        /**
         * EstadoRemapeoModeracion
         * @description Operación física activa visible exclusivamente para Moderación.
         */
        EstadoRemapeoModeracion: {
            /** Remapeo Id */
            remapeo_id: string;
            /** Dispositivo */
            dispositivo: string;
            /** Estado */
            estado: string;
            /** Fingerprint Anterior */
            fingerprint_anterior: string | null;
            /** Candidato */
            candidato: string | null;
            /** Diagnostico */
            diagnostico: string | null;
        };
        /**
         * EstadoRemapeoRespuesta
         * @description Estado físico seguro que la futura UI obtiene por snapshot/SSE.
         */
        EstadoRemapeoRespuesta: {
            /** Remapeo Id */
            remapeo_id: string;
            /** Dispositivo */
            dispositivo: string;
            /** Estado */
            estado: string;
            /** Fingerprint Anterior */
            fingerprint_anterior: string | null;
            /** Candidato */
            candidato: string | null;
            /** Diagnostico */
            diagnostico: string | null;
        };
        /**
         * EstadoVotacion
         * @description Indica exclusivamente si la recepción todavía admite votos.
         * @enum {string}
         */
        EstadoVotacion: "EN_CURSO" | "CERRADA";
        /**
         * EventoPublicoProyectado
         * @description Hecho público seguro derivado de un evento L3 ya confirmado.
         *
         *     El DTO omite deliberadamente nivel, etiqueta y mensaje de auditoría. Su
         *     texto nace de :data:`MAPEO_EVENTOS_PUBLICOS`, por lo que agregar un código
         *     futuro al registro institucional no lo publica de manera accidental.
         */
        EventoPublicoProyectado: {
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: string;
            /** Categoria */
            categoria: string;
            /** Codigo Evento */
            codigo_evento: string;
            /** Texto */
            texto: string;
        };
        /**
         * EventoRecienteProyectado
         * @description Evento cuyo ``fsync`` ya fue confirmado por el escritor activo.
         */
        EventoRecienteProyectado: {
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: string;
            /** Nivel */
            nivel: string;
            /** Etiqueta */
            etiqueta: string;
            /** Codigo Evento */
            codigo_evento: string;
            /** Mensaje */
            mensaje: string;
        };
        FactorEspecial: number;
        FactorNumerico: number;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentidadConcejalRespuesta
         * @description Identidad pública mínima de un concejal asociado al dispositivo.
         */
        IdentidadConcejalRespuesta: {
            /** Dni */
            dni: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Banca */
            banca: number;
        };
        NumeroSesionOmitible: number;
        NumeroVotacion: number;
        /**
         * PersonaPalabraModeracion
         * @description Identidad de cola/orador apropiada para Moderación.
         */
        PersonaPalabraModeracion: {
            /** Dni */
            dni: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Banca */
            banca: number;
        };
        /**
         * PersonaPalabraPublica
         * @description Identidad pública de cola/orador sin DNI.
         */
        PersonaPalabraPublica: {
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Banca */
            banca: number;
        };
        /**
         * PuntoOrdenDelDiaProyectado
         * @description Punto asistencial normalizado disponible solo para Moderación.
         */
        PuntoOrdenDelDiaProyectado: {
            /** Nro Votacion */
            nro_votacion: number;
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            /** Tipo Mayoria */
            tipo_mayoria: string;
            /** Factor */
            factor: number;
            /** Base */
            base: string;
        };
        /**
         * PuntoOrdenDelDiaRespuesta
         * @description Representación normalizada de un punto del Orden del Día en la API.
         *
         *     Expone los campos exactos de DT-039. Para mayoría SIMPLE, factor se expone
         *     como 0 y base como VOTOS_COMPUTABLES.
         */
        PuntoOrdenDelDiaRespuesta: {
            /**
             * Nro Votacion
             * @description Número externo sugerido para la votación (entero >= 1).
             */
            nro_votacion: number;
            /**
             * Tipo
             * @description Tipo descriptivo de votación.
             */
            tipo: string;
            /**
             * Tema
             * @description Tema o asunto a tratar.
             */
            tema: string;
            /** @description Regla de mayoría: SIMPLE o ESPECIAL. */
            tipo_mayoria: components["schemas"]["TipoMayoria"];
            /**
             * Factor
             * @description Factor numérico normalizado (0 para SIMPLE, > 0 y <= 1 para ESPECIAL).
             */
            factor: number;
            /** @description Denominador institucional normalizado: VOTOS_COMPUTABLES, PRESENTES o CUERPO. */
            base: components["schemas"]["BaseMayoria"];
        };
        /**
         * RespuestaSalud
         * @description Respuesta pública mínima, sin datos funcionales ni institucionales.
         */
        RespuestaSalud: {
            /**
             * Estado
             * @default ok
             * @constant
             */
            estado: "ok";
        };
        /**
         * RespuestaTecla
         * @description Forma estable de éxito o rechazo funcional normal de una pulsación.
         */
        RespuestaTecla: {
            /** Aceptada */
            aceptada: boolean;
            /** Dispositivo */
            dispositivo: string;
            /** Tecla */
            tecla: string;
            /** Motivo */
            motivo: string;
            concejal: components["schemas"]["IdentidadConcejalRespuesta"] | null;
            /** Resultado */
            resultado: components["schemas"]["ResultadoPresenciaRespuesta"] | components["schemas"]["ResultadoTestRespuesta"] | components["schemas"]["ResultadoVotoRespuesta"] | components["schemas"]["ResultadoPalabraRespuesta"] | null;
        };
        /**
         * RespuestaVotacion
         * @description Representación HTTP mínima y normalizada de la votación creada.
         */
        RespuestaVotacion: {
            /** Id */
            id: string;
            /** Numero Votacion */
            numero_votacion: number;
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            tipo_mayoria: components["schemas"]["TipoMayoria"];
            /** Factor */
            factor: number;
            base: components["schemas"]["BaseMayoria"];
            estado: components["schemas"]["EstadoVotacion"];
            /**
             * Fecha Hora Apertura
             * Format: date-time
             */
            fecha_hora_apertura: string;
        };
        /**
         * ResultadoPalabraRespuesta
         * @description Resultado tipado de una tecla ``7`` aceptada.
         */
        ResultadoPalabraRespuesta: {
            /**
             * Tipo
             * @constant
             */
            tipo: "PALABRA";
            accion: components["schemas"]["AccionPalabra"];
        };
        /**
         * ResultadoPresenciaRespuesta
         * @description Resultado tipado de una tecla ``9`` aceptada.
         */
        ResultadoPresenciaRespuesta: {
            /**
             * Tipo
             * @constant
             */
            tipo: "PRESENCIA";
            /** Presente */
            presente: boolean;
            /** Presentes */
            presentes: number;
            /** Quorum Alcanzado */
            quorum_alcanzado: boolean;
        };
        /**
         * ResultadoTestRespuesta
         * @description Resultado tipado de una tecla ``8`` aceptada.
         */
        ResultadoTestRespuesta: {
            /**
             * Tipo
             * @constant
             */
            tipo: "TEST";
            /** Activo */
            activo: boolean;
            /** Duracion Segundos */
            duracion_segundos: number;
        };
        /**
         * ResultadoVotoRespuesta
         * @description Resultado tipado de una tecla ``1``, ``2`` o ``3`` aceptada.
         */
        ResultadoVotoRespuesta: {
            /**
             * Tipo
             * @constant
             */
            tipo: "VOTO";
            valor: components["schemas"]["ValorVotoOrdinario"];
            estado_recepcion: components["schemas"]["EstadoVotacion"];
        };
        /**
         * SolicitudActualizarPreparacion
         * @description Body parcial para número y autoridades durante ``PREPARANDO``.
         *
         *     Cada propiedad puede omitirse, pero el body debe contener al menos una.
         *     Los textos vacíos son válidos aquí porque significan limpiar la autoridad.
         *     El entero estricto evita la coerción de booleanos, floats y strings.
         */
        SolicitudActualizarPreparacion: {
            numero_sesion?: components["schemas"]["NumeroSesionOmitible"];
            presidencia?: components["schemas"]["TextoOmitible"];
            secretaria_legislativa?: components["schemas"]["TextoOmitible"];
        };
        /**
         * SolicitudActualizarSesion
         * @description Body parcial para autoridades de una sesión abierta.
         *
         *     El modelo no declara ``numero_sesion`` y prohíbe extras, de modo que todo
         *     intento de editarlo produce 422. Una autoridad suministrada se normaliza en
         *     el servicio, pero debe contener algo distinto de espacios.
         */
        SolicitudActualizarSesion: {
            presidencia?: components["schemas"]["TextoOmitible"];
            secretaria_legislativa?: components["schemas"]["TextoOmitible"];
        };
        /**
         * SolicitudCandidatoRemapeo
         * @description Callback interno del bridge; nunca se expone en ClienteModeracion.
         */
        SolicitudCandidatoRemapeo: {
            /** Fingerprint */
            fingerprint: string;
            /** Diagnostico */
            diagnostico?: string | null;
        };
        /**
         * SolicitudConfirmarRemapeo
         * @description Decisión humana cerrada; no admite coerciones ni otros modos.
         */
        SolicitudConfirmarRemapeo: {
            /**
             * Persistencia
             * @enum {string}
             */
            persistencia: "TEMPORAL" | "PERSISTENTE";
        };
        /**
         * SolicitudDesempate
         * @description Body cerrado del único comando presidencial definido por DEC-012.
         *
         *     El cliente solo elige el sentido. La identidad de Presidencia se obtiene
         *     de la sesión activa dentro del serializador y no puede inyectarse mediante
         *     campos adicionales.
         */
        SolicitudDesempate: {
            /**
             * Sentido
             * @enum {string}
             */
            sentido: "POSITIVO" | "NEGATIVO";
        };
        /**
         * SolicitudFinalizarVotacion
         * @description Body exacto de la finalización manual anticipada de DEC-011.
         *
         *     ``strict=True`` evita convertir booleanos, números u otras estructuras en
         *     texto. El validador normaliza antes de llegar al dominio y rechaza tanto la
         *     cadena vacía como la compuesta únicamente por espacios.
         */
        SolicitudFinalizarVotacion: {
            /** Motivo */
            motivo: string;
        };
        /**
         * SolicitudIniciarRemapeo
         * @description Body cerrado para seleccionar un devXX existente del padrón activo.
         */
        SolicitudIniciarRemapeo: {
            /** Dispositivo */
            dispositivo: string;
        };
        /**
         * SolicitudTecla
         * @description Body exacto de la pulsación lógica que recibe el backend.
         *
         *     ``extra='forbid'`` hace que DNI, banca, fingerprint u otros datos que no
         *     pertenecen al contrato produzcan ``422`` en vez de ser ignorados. El bridge
         *     ya debe haber resuelto lo físico a un dispositivo lógico antes de llamar a
         *     esta ruta.
         */
        SolicitudTecla: {
            /** Dispositivo */
            dispositivo: string;
            /** Tecla */
            tecla: string;
        };
        /**
         * SolicitudVotacionEspecial
         * @description Variante ESPECIAL con factor finito y una base canónica obligatoria.
         */
        SolicitudVotacionEspecial: {
            numero_votacion: components["schemas"]["NumeroVotacion"];
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo_mayoria: "ESPECIAL";
            factor: components["schemas"]["FactorEspecial"];
            base: components["schemas"]["BaseMayoria"];
        };
        /**
         * SolicitudVotacionSimple
         * @description Variante SIMPLE con factor/base opcionales y salida normalizada.
         *
         *     Un factor omitido, nulo o numéricamente cero es equivalente. Toda base
         *     distinta de ``VOTOS_COMPUTABLES`` queda fuera del propio esquema de esta
         *     variante y por eso FastAPI responde 422 antes de invocar el servicio.
         */
        SolicitudVotacionSimple: {
            numero_votacion: components["schemas"]["NumeroVotacion"];
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo_mayoria: "SIMPLE";
            factor?: components["schemas"]["FactorNumerico"] | null;
            /**
             * Base
             * @default VOTOS_COMPUTABLES
             * @constant
             */
            base: "VOTOS_COMPUTABLES";
        };
        TextoOmitible: string;
        /**
         * TipoMayoria
         * @description Distingue la regla de decisión declarada por Moderación.
         *
         *     El tipo es autoritativo: nunca se deduce una mayoría simple o especial a
         *     partir del factor. Los valores coinciden con el contrato REST de DEC-009.
         * @enum {string}
         */
        TipoMayoria: "SIMPLE" | "ESPECIAL";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValorVotoOrdinario
         * @description Representa los tres valores que puede emitir una banca mediante 1/2/3.
         * @enum {string}
         */
        ValorVotoOrdinario: "POSITIVO" | "ABSTENCION" | "NEGATIVO";
        /**
         * VotacionModeracion
         * @description Vista completa de la votación relevante para el operador.
         */
        VotacionModeracion: {
            /** Id */
            id: string;
            /** Numero Votacion */
            numero_votacion: number;
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            /** Tipo Mayoria */
            tipo_mayoria: string;
            /** Factor */
            factor: number;
            /** Base */
            base: string;
            /** Estado Recepcion */
            estado_recepcion: string;
            /** Resultado */
            resultado: string | null;
            /**
             * Fecha Hora Apertura
             * Format: date-time
             */
            fecha_hora_apertura: string;
            /** Fecha Hora Cierre */
            fecha_hora_cierre: string | null;
            /** Fecha Hora Resultado */
            fecha_hora_resultado: string | null;
            /** Motivo Finalizacion Manual */
            motivo_finalizacion_manual: string | null;
            /** Cantidad Votos Recibidos */
            cantidad_votos_recibidos: number;
            /** Bancas Voto Emitido */
            bancas_voto_emitido: number[];
            /**
             * Revelado Individual Desde
             * Format: date-time
             */
            revelado_individual_desde: string;
            /** Votos Individuales Revelados */
            votos_individuales_revelados: boolean;
            /** Votos Individuales */
            votos_individuales: components["schemas"]["VotoModeracion"][] | null;
            conteos: components["schemas"]["ConteosVotosProyectados"] | null;
            voto_presidencial: components["schemas"]["VotoPresidencialProyectado"] | null;
        };
        /**
         * VotacionPublica
         * @description Vista pública restrictiva construida sin serializar el dominio completo.
         */
        VotacionPublica: {
            /** Id */
            id: string;
            /** Numero Votacion */
            numero_votacion: number;
            /** Tipo */
            tipo: string;
            /** Tema */
            tema: string;
            /** Tipo Mayoria */
            tipo_mayoria: string;
            /** Factor */
            factor: number;
            /** Base */
            base: string;
            /** Estado Recepcion */
            estado_recepcion: string;
            /** Resultado */
            resultado: string | null;
            /**
             * Fecha Hora Apertura
             * Format: date-time
             */
            fecha_hora_apertura: string;
            /** Fecha Hora Cierre */
            fecha_hora_cierre: string | null;
            /** Cuenta Regresiva Hasta */
            cuenta_regresiva_hasta: string | null;
            /** Resultado Visible Hasta */
            resultado_visible_hasta: string | null;
            /** Bancas Voto Emitido */
            bancas_voto_emitido: number[];
            /** Votos Individuales */
            votos_individuales: components["schemas"]["VotoPublico"][] | null;
            conteos: components["schemas"]["ConteosVotosProyectados"] | null;
            voto_presidencial: components["schemas"]["VotoPresidencialProyectado"] | null;
        };
        /**
         * VotoModeracion
         * @description Voto ordinario individual revelable a Moderación según su deadline.
         */
        VotoModeracion: {
            /** Dni */
            dni: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Banca */
            banca: number;
            /** Valor */
            valor: string;
        };
        /**
         * VotoPresidencialProyectado
         * @description Desempate separado que no se mezcla con los votos de concejales.
         */
        VotoPresidencialProyectado: {
            /** Presidencia */
            presidencia: string;
            /** Sentido */
            sentido: string;
        };
        /**
         * VotoPublico
         * @description Voto ordinario público posterior al cierre, asociado solo a la banca.
         */
        VotoPublico: {
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Banca */
            banca: number;
            /** Valor */
            valor: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultar_salud_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaSalud"];
                };
            };
        };
    };
    preparar_sala_api_v1_preparacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El comando no es válido para el estado global actual (ESTADO_INCOMPATIBLE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad técnica: CONFIGURACION_INVALIDA, PADRON_INVALIDO o AUDITORIA_NO_DISPONIBLE según el caso. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    cancelar_preparacion_api_v1_preparacion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El comando no es válido para el estado global actual (ESTADO_INCOMPATIBLE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad técnica: CONFIGURACION_INVALIDA, PADRON_INVALIDO o AUDITORIA_NO_DISPONIBLE según el caso. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    actualizar_preparacion_api_v1_preparacion_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudActualizarPreparacion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El comando no es válido para el estado global actual (ESTADO_INCOMPATIBLE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Body vacío/inválido o número que no es entero estricto positivo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad técnica: CONFIGURACION_INVALIDA, PADRON_INVALIDO o AUDITORIA_NO_DISPONIBLE según el caso. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    abrir_sesion_api_v1_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo funcional con código estable según la precondición. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La solicitud no cumple el contrato de transporte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    cerrar_sesion_api_v1_sesion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo funcional con código estable según la precondición. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La solicitud no cumple el contrato de transporte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    actualizar_sesion_api_v1_sesion_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudActualizarSesion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo funcional con código estable según la precondición. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La solicitud no cumple el contrato de transporte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    abrir_votacion_api_v1_votaciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudVotacionSimple"] | components["schemas"]["SolicitudVotacionEspecial"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaVotacion"];
                };
            };
            /** @description Estado, quórum o votación pendiente impiden la apertura. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Body inválido o tipo descriptivo no permitido por la configuración congelada. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    finalizar_votacion_api_v1_votaciones__id__finalizacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudFinalizarVotacion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo funcional: ESTADO_INCOMPATIBLE, VOTACION_NO_COINCIDE o VOTACION_NO_EN_CURSO. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description El path o body no cumple el contrato estricto de transporte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    desempatar_votacion_api_v1_votaciones__id__desempate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDesempate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo funcional: ESTADO_INCOMPATIBLE, VOTACION_NO_COINCIDE, VOTACION_NO_EMPATADA o DESEMPATE_YA_EMITIDO. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description El path o body no cumple el contrato estricto de transporte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    procesar_tecla_api_v1_entradas_tecla_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudTecla"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaTecla"];
                };
            };
            /** @description El body no cumple el esquema de transporte de la pulsación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    cargar_orden_del_dia_api_v1_orden_del_dia_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_cargar_orden_del_dia_api_v1_orden_del_dia_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargaOrdenDelDiaRespuesta"];
                };
            };
            /** @description Estado incompatible (intento de carga en SIN_PREPARAR). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Archivo recibido pero técnicamente inválido (ORDEN_DEL_DIA_INVALIDO). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Error interno inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Auditoría obligatoria no disponible (AUDITORIA_NO_DISPONIBLE). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    descartar_orden_del_dia_api_v1_orden_del_dia_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Estado incompatible (intento de descarte en SIN_PREPARAR). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Error interno inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Auditoría obligatoria no disponible (AUDITORIA_NO_DISPONIBLE). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    otorgar_palabra_api_v1_palabra_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe una sesión abierta (ESTADO_INCOMPATIBLE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    quitar_palabra_api_v1_palabra_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe una sesión abierta (ESTADO_INCOMPATIBLE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Fallo inesperado no clasificado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No puede garantizarse la auditoría obligatoria. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    obtener_estado_moderacion_api_v1_estado_moderacion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoModeracion"];
                };
            };
        };
    };
    obtener_estado_recinto_api_v1_estado_recinto_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoRecinto"];
                };
            };
        };
    };
    transmitir_estado_moderacion_api_v1_estado_moderacion_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Server-Sent Events. Cada evento `estado` contiene un EstadoModeracion completo; `id` coincide con su revision. No transporta deltas ni ofrece replay durable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    transmitir_estado_recinto_api_v1_estado_recinto_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Server-Sent Events. Cada evento `estado` contiene un EstadoRecinto completo con el secreto público aplicado en servidor; `id` coincide con su revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    iniciar_remapeo_api_v1_remapeos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudIniciarRemapeo"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoRemapeoRespuesta"];
                };
            };
            /** @description Conflicto funcional: ESTADO_INCOMPATIBLE, DISPOSITIVO_REMAPEO_NO_EXISTENTE, REMAPEO_YA_ACTIVO, REMAPEO_NO_COINCIDE, REMAPEO_SIN_CANDIDATO, CANDIDATO_YA_REGISTRADO o PARAMETROS_REMAPEO_INCOMPATIBLES. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Fallo inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad: BRIDGE_NO_DISPONIBLE, APLICACION_BRIDGE_RECHAZADA o AUDITORIA_NO_DISPONIBLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    informar_candidato_api_v1_interno_remapeos__remapeo_id__candidato_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remapeo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCandidatoRemapeo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoRemapeoRespuesta"];
                };
            };
            /** @description Conflicto funcional: ESTADO_INCOMPATIBLE, DISPOSITIVO_REMAPEO_NO_EXISTENTE, REMAPEO_YA_ACTIVO, REMAPEO_NO_COINCIDE, REMAPEO_SIN_CANDIDATO, CANDIDATO_YA_REGISTRADO o PARAMETROS_REMAPEO_INCOMPATIBLES. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Fallo inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad: BRIDGE_NO_DISPONIBLE, APLICACION_BRIDGE_RECHAZADA o AUDITORIA_NO_DISPONIBLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    confirmar_remapeo_api_v1_remapeos__remapeo_id__confirmacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remapeo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudConfirmarRemapeo"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflicto funcional: ESTADO_INCOMPATIBLE, DISPOSITIVO_REMAPEO_NO_EXISTENTE, REMAPEO_YA_ACTIVO, REMAPEO_NO_COINCIDE, REMAPEO_SIN_CANDIDATO, CANDIDATO_YA_REGISTRADO o PARAMETROS_REMAPEO_INCOMPATIBLES. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Fallo inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad: BRIDGE_NO_DISPONIBLE, APLICACION_BRIDGE_RECHAZADA o AUDITORIA_NO_DISPONIBLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    cancelar_remapeo_api_v1_remapeos__remapeo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remapeo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflicto funcional: ESTADO_INCOMPATIBLE, DISPOSITIVO_REMAPEO_NO_EXISTENTE, REMAPEO_YA_ACTIVO, REMAPEO_NO_COINCIDE, REMAPEO_SIN_CANDIDATO, CANDIDATO_YA_REGISTRADO o PARAMETROS_REMAPEO_INCOMPATIBLES. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Fallo inesperado (ERROR_INTERNO). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Indisponibilidad: BRIDGE_NO_DISPONIBLE, APLICACION_BRIDGE_RECHAZADA o AUDITORIA_NO_DISPONIBLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
}
